apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: fastapi-app
  ports:
    - port: 80
     
      targetPort: 80
   
      nodePort: 30007
